;***********************************************************************
;*  MP3VE - Standalone MP3 Player
;*  Copyright (C) 2000,2001,2002 Marc Dressler, Jens Funke,
;*                               Thomas Gutzeit, Nils Steenbock
;*
;*  This program is free software; you can redistribute it and/or modify
;*  it under the terms of the GNU General Public License as published by
;*  the Free Software Foundation; either version 2 of the License, or
;*  (at your option) any later version.
;*
;*  This program is distributed in the hope that it will be useful,
;*  but WITHOUT ANY WARRANTY; without even the implied warranty of
;*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;*  GNU General Public License for more details.
;*
;*  You should have received a copy of the GNU General Public License
;*  along with this program; if not, write to the Free Software
;*  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
;*
;*  info@mp3ve.de
;***********************************************************************

;***********************************************************************
;* $Id: example.inc,v 1.1 2002/07/31 17:31:59 dressler Exp $
;***********************************************************************
;*
;*  Title     	: Example for documentation standards
;*  Version     : 1.5
;*				
;*  Filename    : example.inc
;*  Created     : dd.mm.yyyy by name
;*  Last changed: dd.mm.yyyy by name
;*	
;*  Target-uC   : Atmel AVR AT90Sxxxx
;*  Target-PCB  : ExpBoard8515
;*  Description : does nothing
;*
;*  Homepage    : www.MP3ve.de
;*                www.uC-Elektronik.de
;*                www.Hardware-Schmiede.de	
;*
;*  Uses        : example.inc
;*
;***********************************************************************

;***********************************************************************
;* GLOBAL DEFINITIONS			;!!! MAIN-FILE ONLY !!!
;***********************************************************************

	INCLUDE ""

;***********************************************************************
;* USER DEFINITIONS
;***********************************************************************

	EQU	

;***********************************************************************
;* PRIVATE DEFINITIONS
;***********************************************************************

	EQU	

;***********************************************************************
;* FUNCTION	: functionname 1 
;*              
;* CREATED	: dd.mm.yyyy by name
;*              
;* LAST CHANGED : dd.mm.yyyy by name
;*              
;* DESCRIPTION  : doeseverythingornothing
;*              
;* INPUT        : inputparametername1 - character to display
;*                inputparametername2 - cursor x-position 
;*              
;* OUTPUT       : samewayasinput
;*
;***********************************************************************

;***********************************************************************
;* FUNCTION	: functionname 2
;*              
;* CREATED	: dd.mm.yyyy by name
;*              
;* LAST CHANGED : dd.mm.yyyy by name
;*              
;* DESCRIPTION  : doeseverythingornothing
;*              
;* INPUT        : -
;*              
;* OUTPUT       : -
;*
;***********************************************************************

;***********************************************************************
;* INCLUDE FILES
;***********************************************************************

	INCLUDE ""

;***********************************************************************
;* CONSTANTS DECLARATION IN CODE SEGMENT
;***********************************************************************

	SEGMENT CODE

;***********************************************************************
;* VARIABLE DECLARATION IN DATA SEGMENT
;***********************************************************************

	SEGMENT DATA

;***********************************************************************
;* VARIABLE DECLARATION IN EEPROM SEGMENT
;***********************************************************************

;	SEGMENT ?XXXX?	; not supported in AS

;***********************************************************************
;* Notes
;***********************************************************************


;*
;* $Log: example.inc,v $
;* Revision 1.1  2002/07/31 17:31:59  dressler
;* initial checkin
;*
